version: 2
updates:
- package-ecosystem: github-actions
  directory: "/.github/actions/setup-env"
  schedule:
    interval: daily
    time: "06:00"
  open-pull-requests-limit: 5
  assignees:
  - Shawn8901
  labels:
  - CI
- package-ecosystem: github-actions
  directory: "/.github/actions/update-custom-branch"
  schedule:
    interval: daily
    time: "06:00"
  open-pull-requests-limit: 5
  assignees:
  - Shawn8901
  labels:
  - CI

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
    time: "06:00"
  open-pull-requests-limit: 5
  assignees:
  - Shawn8901
  labels:
  - CI
