name: "update-custom-branch"
description: "Does rebase the custom branch on top of upstream"
inputs:
  base_branch:
    description: "Custom branch for a release to be synced"
    required: true
  gh_token:
    description: "GH Token used for pushing the content"
    required: true
  working_dir:
    description: "dir that this applies on"
    required: true
runs:
  using: "composite"
  steps:
    - name: Update custom ${{ inputs.base_branch }} branch
      working-directory: ${{ inputs.working_dir }}
      shell: bash
      run: |
        git checkout ${{ inputs.base_branch }}-custom
        commits_ahead=$(git rev-list --count ${{ inputs.base_branch }}-custom..origin/${{ inputs.base_branch }})
        echo "base branch ${{ inputs.base_branch }} is $commits_ahead commits ahead"
        if [ $commits_ahead -eq 0 ]
        then
          exit 0
        fi
        git rebase origin/${{ inputs.base_branch }}
        git push --force-with-lease
      env:
        GH_TOKEN: "${{ inputs.gh_token }}"
