name: "setup-env"
description: "Does to lifting to install nix and setup cachix on the runner"
inputs:
  github_token:
    description: "Token to be used for Github"
    required: true
  netrc_content:
    description: "Content for the netrc"
    required: true
runs:
  using: "composite"
  steps:
    - name: Generate netrc
      shell: bash
      run: echo "${{ inputs.netrc_content }}" > /home/runner/.netrc
    - name: Install nix
      uses: nixbuild/nix-quick-install-action@63ca48f939ee3b8d835f4126562537df0fee5b91 # v32
      with:
        github_access_token: ${{ inputs.github_token }}
        nix_conf: |
          netrc-file = /home/runner/.netrc
          substituters = https://cache.nixos.org https://nix-community.cachix.org https://cache.pointjig.de/nixos
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= nixos:5axzveeiERb8xAeioBUHNHq4SVLvwDcJkLMFsWq0l1E=
    - uses: nix-community/cache-nix-action@135667ec418502fa5a3598af6fb9eb733888ce6a # v6.1.3
      with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
