name: "setup-env"
description: "Does to lifting to install nix and setup cachix on the runner"
inputs:
  github_token:
    description: "Token to be used for Github"
    required: true
  netrc_content:
    description: "Content for the netrc"
    required: true
runs:
  using: "composite"
  steps:
    - name: Generate netrc
      shell: bash
      run: echo "${{ inputs.netrc_content }}" > /home/runner/.netrc
    - name: Install nix
      uses: cachix/install-nix-action@17fe5fb4a23ad6cbbe47d6b3f359611ad276644c # v31.4.0
      with:
        extra_nix_config: |
          auto-optimise-store = true
          access-tokens = github.com=${{ inputs.github_token }}
          experimental-features = nix-command flakes
          netrc-file = /home/runner/.netrc
          substituters = https://cache.nixos.org https://nix-community.cachix.org https://cache.pointjig.de/nixos
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= nixos:5axzveeiERb8xAeioBUHNHq4SVLvwDcJkLMFsWq0l1E=
    - uses: nix-community/cache-nix-action@135667ec418502fa5a3598af6fb9eb733888ce6a # v6.1.3
      with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1073741824
          purge: false
